# Generated by Django 5.2.1 on 2025-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mood_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='title',
            field=models.TextField(default="today's mood", help_text='Title of the moodNote'),
        ),
    ]
